services:
  postgres-db:
    image: postgres:15-alpine
    container_name: adventures-service-db
    environment:
      - POSTGRES_USER=roberto
      - POSTGRES_PASSWORD=roberto
      - POSTGRES_DB=adventures
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U roberto -d adventures"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: